import random

def get_positive_word():
    words = [
        "AMOR", "LUZ", "PAZ", "FÉ", "RISA", "BUENO", "BELLO", "CLARO", "GANA", "LUJO",
        "CIELO", "FELIZ", "GRATO", "SOL", "LEAL", "AMIGO", "LUCHAR", "GRANDE", "DULCE",
        "ÉXITO", "GARBO", "SANO", "GARANTÍA", "GENIAL", "UNIÓN", "SABIO", "ÍDOLO", "IDEAL",
        "JOYA", "ALEGRE", "MEJOR", "FÁCIL", "RICO", "ABRAZO", "GOZO", "SERENO", "SONREÍR",
        "AMABLE", "SORPRESA", "BONITO", "VIRTUD", "RADIO", "TIEMPO", "BRILLO", "CORAZÓN",
        "DESEO", "DIGNO", "SABER", "SABIDURÍA", "LOGRO", "ACIERTO", "SUEÑO", "ALEGRÍA",
        "FORTUNA", "GRACIA", "FELICIDAD", "BELLEZA", "LUJOSO", "ELEGANTE", "ALEGRÍA", "SALUD",
        "SERENIDAD", "SONRISA", "VALOR", "RISA", "VICTORIA", "VISIÓN", "ZENITH",
        "OPTIMISMO", "AFABLE", "AFECTO", "AGRADECER", "AMISTAD", "BENDICIÓN", "CALIDEZ",
        "CARIÑO", "COHERENTE", "COLABORAR", "DECISIVO", "DELICADO", "DINÁMICO", "ECUÁNIME",
        "EMPATÍA", "ENTUSIASMO", "ESPERANZA", "ETERNIDAD", "FORTALEZA", "GENEROSO", "GRATITUD",
        "HUMILDAD", "ILUSIÓN", "INNOVAR", "INTEGRIDAD", "LIBERTAD", "LIDERAR", "MARAVILLA",
        "NATURALEZA", "NOVEDAD", "PACIENCIA", "PAZ", "PROGRESO", "QUERENCIA", "RECONCILIACIÓN",
        "SABIDURÍA", "SALUD", "SERENIDAD", "SOLIDARIDAD", "TOLERANCIA", "TRANQUILIDAD", "TRIUNFO",
        "VICTORIA", "VITALIDAD", "ARMONÍA", "AVANCE", "BENEVOLENCIA", "BONDAD", "CÁLIDO",
        "CERTEZA", "COMPAÑERO", "CONFIANZA", "CONFIAR", "CRECER", "CREER", "DELICIA", "DESARROLLAR",
        "EDIFICAR", "ELEGANCIA", "EMPEÑO", "ENFOCAR", "ESFUERZO", "ÉXITO", "FORTUNADO", "GRATO",
        "HÉROE", "HONESTIDAD", "ILUMINAR", "INICIAR", "INNOVACIÓN", "INTEGRAR", "MAGIA", "MARAVILLOSO",
        "MOTIVAR", "NUEVO", "PACIENTE", "PERSISTIR", "POSITIVO", "SABIO", "SALUDABLE", "SERENO",
        "SINCERIDAD", "SORPRENDER", "TRANQUILIZAR", "TRIUNFAR", "VALIOSO", "VIBRANTE", "VIGOROSO",
        "VIRTUOSO", "VITALIDAD"
    ]

    pickup_position = random.randint(0,len(words)-1)
    return words[pickup_position]

