# Build environment.
[envs.hatch-build]
dependencies = ["cython"]

# Wheel build configuration
[build.targets.wheel]
packages = ["bindings/python/rgbmatrix"]
exclude = [
    "*.cpp",
    "*.pyd",
    "*.pyx"
    ]
artifacts = ["*.so"]

# External hook script which invokes the makefile to build C library.
[build.targets.wheel.hooks.custom]
dependencies = ["cython"]
path = "build-rpi-rgb-led-matrix.py"

[build.targets.wheel.hooks.cython]
dependencies = ["hatch-cython"]

[build.targets.wheel.hooks.cython.options]
src = "src/bindings/python/rgbmatrix"
includes = ["../../include"]
libraries = "rgbmatrix"
library_dirs = ["../../lib"]
compile_args = ["-O3", "-Wall"]
