import random

def get_command():
    commands = [
        "ls -l",
        "git com",
        "dir",
        "rm -r",
        "cat -f",
        "mkdir",
        "echo str",
        "touch -f",
        "cd",
        "cp f1 f2",
        "mv f1 f2",
        "rmdir",
        "sort -f",
        "grep",
        "find .",
        "wc -l -f",
        "head -f",
        "tail -f",
        "chmod +x",
        "chown ",
        "ps -ef",
        "kill PID",
        "top",
        "ping host",
        "ifconfig",
        "ipconfig",
        "netstat",
        "route",
        "traceroute",
        "hostname",
        "whoami",
        "who",
        "finger",
        "uptime",
        "date",
        "cal",
        "df",
        "du",
        "free",
        "ps",
        "kill",
        "pkill",
        "pgrep",
        "killall",
        "nice",
        "renice",
        "psaux",
        "pstree",
        "bg",
        "fg",
        "jobs",
        "killall",
        "pmap",
        "strace",
        "dmesg",
        "lsblk",
        "fdisk",
        "mount",
        "umount",
        "df",
        "du",
        "lsof",
        "fuser",
        "netstat",
        "ss",
        "ip",
        "route",
        "arp",
        "iptables",
        "tcpdump",
        "ping",
        "traceroute",
        "host",
        "nslookup",
        "dig",
        "wget",
        "curl",
        "scp",
        "ssh",
        "rsync",
        "tar",
        "gzip",
        "bzip2",
        "zip",
        "unzip",
        "chmod",
        "chown",
        "chgrp",
        "useradd",
        "userdel",
        "passwd",
        "groupadd",
        "groupdel",
        "usermod",
        "adduser",
        "deluser",
        "addgroup",
        "delgroup",
        "passwd",
        "sudo",
        "visudo",
        "su",
        "sudoedit",
        "chsh",
        "chfn",
        "usermod",
        "groupmod",
        "id",
        "who",
        "w",
        "finger",
        "last",
        "history",
        "clear",
        "exit",
        "git pull",
        "git push",
        "git rebase",
        "git merge",
        "git commit",
    ]

    pickup_position = random.randint(0,len(commands)-1)
    return commands[pickup_position]

