import random

def get_command():
    commands = [
        "ls -l",
        "git com",
        "dir",
        "rm -r",
        "cat file",
        "mkdir dir",
        "echo hello",
        "touch file",
        "cd dir",
        "cp file1 file2",
        "mv file1 file2",
        "rmdir dir",
        "sort file",
        "grep pattern file",
        "find . -type f",
        "wc -l file",
        "head file",
        "tail file",
        "chmod 755 file",
        "chown user:group file",
        "ps -ef",
        "kill PID",
        "top",
        "ping host",
        "ifconfig",
        "ipconfig",
        "netstat",
        "route",
        "traceroute host",
        "hostname",
        "whoami",
        "who",
        "finger user",
        "uptime",
        "date",
        "cal",
        "df",
        "du",
        "free",
        "ps",
        "kill",
        "pkill",
        "pgrep",
        "killall",
        "nice",
        "renice",
        "psaux",
        "pstree",
        "bg",
        "fg",
        "jobs",
        "killall",
        "pmap",
        "strace",
        "dmesg",
        "lsblk",
        "fdisk",
        "mount",
        "umount",
        "df",
        "du",
        "lsof",
        "fuser",
        "netstat",
        "ss",
        "ip",
        "route",
        "arp",
        "iptables",
        "tcpdump",
        "ping",
        "traceroute",
        "host",
        "nslookup",
        "dig",
        "wget",
        "curl",
        "scp",
        "ssh",
        "rsync",
        "tar",
        "gzip",
        "bzip2",
        "zip",
        "unzip",
        "chmod",
        "chown",
        "chgrp",
        "useradd",
        "userdel",
        "passwd",
        "groupadd",
        "groupdel",
        "usermod",
        "adduser",
        "deluser",
        "addgroup",
        "delgroup",
        "passwd",
        "sudo",
        "visudo",
        "su",
        "sudoedit",
        "chsh",
        "chfn",
        "usermod",
        "groupmod",
        "id",
        "who",
        "w",
        "finger",
        "last",
        "history",
        "clear",
        "exit"
    ]

    pickup_position = random.randint(0,len(commands)-1)
    return commands[pickup_position]

