import random

def get_positive_word():
    words = [
        "AMOR", "LUZ", "PAZ", "FÉ", "RISA", "BUENO", "BELLO", "CLARO", "GANA", "LUJO",
        "CIELO", "FELIZ", "GRATO", "SOL", "LEAL", "AMIGO", "LUCHAR", "GRANDE", "DULCE",
        "ÉXITO", "GARBO", "SANO", "GARANTÍA", "GENIAL", "UNIÓN", "SABIO", "ÍDOLO", "IDEAL",
        "JOYA", "ALEGRE", "MEJOR", "FÁCIL", "RICO", "ABRAZO", "SERENO", "SONREÍR",
        "AMABLE", "SORPRESA", "BONITO", "VIRTUD", "TIEMPO", "BRILLO", "CORAZÓN",
        "DESEO", "DIGNO", "SABER", "SABIDURÍA", "LOGRO", "ACIERTO", "SUEÑOS", "ALEGRÍA",
        "FORTUNA", "GRACIA", "FELICIDAD", "BELLEZA", "LUJOSO", "ELEGANTE", "ALEGRÍA", "SALUD",
        "SONRISA", "VALOR", "RISA", "VICTORIA", "VISIÓN", "AFABLE", "AFECTO", "AGRADECER",
        "AMISTAD", "CALIDEZ", "CARIÑO", "COHERENTE", "DECISIVO", "DELICADO", "DINÁMICO", "ECUÁNIME",
        "EMPATÍA", "ENTUSIASMO", "ESPERANZA", "ETERNIDAD", "FORTALEZA", "GENEROSO", "GRATITUD",
        "HUMILDAD", "ILUSIÓN", "INNOVAR", "INTEGRIDAD", "LIBERTAD", "LIDERAR", "MARAVILLA",
        "NATURAL", "NOVEDAD", "PACIENCIA", "PAZ", "PROGRESO", "QUERENCIA", "RECONCILIACIÓN",
        "SABIDURÍA", "SALUD", "SERENIDAD", "SOLIDARIDAD", "TOLERANCIA", "TRANQUILIDAD", "TRIUNFO",
        "VICTORIA", "VITALIDAD", "ARMONÍA", "AVANCE", "BENEVOLENCIA", "BONDAD", "CÁLIDO",
        "CERTEZA", "COMPAÑERO", "CONFIANZA", "CONFIAR", "CRECER", "CREER", "DELICIA",
        "EDIFICAR", "ELEGANCIA", "EMPEÑO", "ENFOCAR", "ESFUERZO", "ÉXITO", "FORTUNADO", "GRATO",
        "HÉROE", "HONESTIDAD", "ILUMINAR", "INICIAR", "INNOVACIÓN", "INTEGRAR", "MAGIA",
        "MOTIVAR", "NUEVO", "PACIENTE", "PERSISTIR", "POSITIVO", "SABIO", "SALUDABLE", "SERENO",
        "LOVE", "LIGHT", "PEACE", "FAITH", "SMILE", "GOOD", "BEAUTY", "CLEAR", "GAIN", "LUXURY",
        "SKY", "HAPPY", "GRATE", "SUN", "LOYAL", "FRIEND", "FIGHT", "LARGE", "SWEET",
        "SUCCESS", "GRACE", "HEALTHY", "GUARANTEE", "GREAT", "UNITY", "WISE", "IDOL", "IDEAL",
        "GEM", "CHEER", "BETTER", "EASY", "RICH", "HUG", "SERENE", "SMILE",
        "KIND", "SURPRISE", "PRETTY", "VIRTUE", "TIME", "SHINE", "HEART",
        "WISH", "WORTHY", "KNOW", "WISDOM", "ACHIEVE", "SUCCESS", "DREAMS", "JOY",
        "FORTUNE", "GRACE", "HAPPINESS", "BEAUTY", "LUXURIOUS", "ELEGANT", "JOY", "HEALTH",
        "SMILE", "VALUE", "LAUGH", "VICTORY", "VISION", "AMICABLE", "AFFECTION", "THANKFUL",
        "FRIENDSHIP", "WARMTH", "LOVE", "COHERENT", "DECISIVE", "DELICATE", "DYNAMIC", "EQUITABLE",
        "EMPATHY", "ENTHUSIASM", "HOPE", "ETERNITY", "STRENGTH", "GENEROSITY", "GRATITUDE",
        "HUMILITY", "ILLUSION", "INNOVATE", "INTEGRITY", "FREEDOM", "LEAD", "MARVEL",
        "NATURAL", "NOVELTY", "PATIENCE", "PEACE", "PROGRESS", "TENDERNESS", "RECONCILIATION",
        "WISDOM", "HEALTH", "SERENITY", "SOLIDARITY", "TOLERANCE", "TRANQUILITY", "TRIUMPH",
        "VICTORY", "VITALITY", "HARMONY", "ADVANCE", "BENEVOLENCE", "GOODNESS", "WARM",
        "CERTAINTY", "COMPANION", "TRUST", "BELIEVE", "GROW", "DELIGHT",
        "BUILD", "ELEGANCE", "EFFORT", "FOCUS", "STRIVE", "SUCCESS", "FORTUNATE", "GRATEFUL",
        "HERO", "HONESTY", "ILLUMINATE", "BEGIN", "INNOVATION", "INTEGRATE", "MAGIC",
        "MOTIVATE", "NEW", "PATIENT", "PERSIST", "POSITIVE", "WISE", "HEALTHY", "SERENE",
        "SINCERITY", "SURPRISE", "CALM", "TRIUMPH", "VALUABLE", "VIBRANT", "VIGOROUS",
    ]

    pickup_position = random.randint(0,len(words)-1)
    return words[pickup_position]

