open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  (* Create function bindings *)
  let matrix_create_from_options =
    foreign "led_matrix_create_from_options"
      ((ptr Types.Options.t @->
        ptr int @->
        ptr (ptr (ptr char)) @->
        returning (ptr Types.matrix)))

  let matrix_create_from_options_const_argv =
    foreign "led_matrix_create_from_options_const_argv"
      ((ptr Types.Options.t @->
        int @->
        ptr (ptr char) @->
        returning (ptr Types.matrix)))

  let matrix_create =
    foreign "led_matrix_create"
      (int @-> int @-> int @-> returning (ptr Types.matrix))

end
